version: "3.8"

services:
  script:
    build: .
    command: [ "python", "main.py" ]
    container_name: script
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    user: postgres
    image: postgres:14
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

